name: Add to Project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest

    steps:
      - name: Add to Project
        run: |
          gh issue create --project "GeorgiBal's diplom project" --status "Todo" --title "${{ github.event.issue.title }}" --body "${{ github.event.issue.body }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

